version: '4'
services:
  postgresql:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DATABASE=postgres
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis
    ports:
      - 6379:6379
